package com.consultorio.casos_judiciales.enums;

public enum Permission {
READ_ALL_CLIENT_ROLE,
READ_ALL_CLIENT,
CREATE_CASE,
READ_CASE,
READ_ALL_CASES,
UPDATE_CASE,
DELETE_CASE,
CREATE_PERSONA,
READ_PERSONA,
UPDATE_PERSONA,
DELETE_PERSONA,
CREATE_ADMIN,
CREATE_ABOGADO
}
