package com.consultorio.casos_judiciales.utils;

public enum Permission {
CREATE_CASE,
READ_CASE,
UPDATE_CASE,
DELETE_CASE,
CREATE_PERSONA,
READ_PERSONA,
UPDATE_PERSONA,
DELETE_PERSONA,
CREATE_ADMIN,
CREATE_ABOGADO
}
